class ChargeResponse(object):
    """
    Class for charge response
    """
    #: Redirect url, generated by payment gateway
    redirect_url = None
    #: Received amount, returned by payment gateway
    received_amt = None
    #: Raw response should be in dict of payment gateway
    raw = None
    #: Standard status any of transaction.constants.Status
    status = None
    #: Human readable success / fail reason message
    message = None

    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)
